services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: zemon-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://localhost:3000
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zemon-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: zemon-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 