services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: zemon-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://namestekayo:Shivang_0@zemon.dtl9t.mongodb.net/?retryWrites=true&w=majority&appName=zemon
      - JWT_SECRET=3cbdaa747097c1b5deb4495d018fbad7a996065055a88240c3587629645617249121393407285291994686680d198abdb5cc86b0d9503310ea3463e859ea11548a3a112616669fd0c2e5c9a2f669f875b8f18eee9fbf336c4ef65af8f926afb53bf64a1dc24a39e4761dfb51e83e5d504cf17f910b5a0d3e88f8a4df572eeab7d82e0f00169c8e69678afc7ad5203724916dbef559af22ffe4f28cc969fb910cd9333117922b4c63a864136d2803b95c38025315c63fea84eff99efef831ea09a307cc4be6e7d666122ce0862e679b0c4188ec472bc54cf886e087e396ba961af3279148d66f7f0dab3fd2e756057044b2d06e20da84862ae8536958c92ec197
      - FRONTEND_URL=http://localhost
      - PORT=5000
      - CORS_ORIGIN=http://localhost
    networks:
      - app-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zemon-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.production
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: zemon-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 